### ISSUE TITLE
import a pre-populated SQLite database from application for iOS an Android

### ISSUE THREAD

**Issue by vishalpjpt** [craftzdog/react-native-sqlite-2#69] opened 2019-10-24 10:05 UTC
Is there any way to import a prepopulated database for iOS and Android like we have in this plugin 
https://github.com/andpor/react-native-sqlite-storage#importing-a-pre-populated-database

**Comment by craftzdog** [comment] 2019-10-25 05:16
Duplicate of https://github.com/craftzdog/react-native-sqlite-2/issues/54

**Closed by craftzdog** 2019-10-25 05:16 UTC
